### ISSUE TITLE
Invalid directory paths in the readme.txt file

### ISSUE THREAD

**Issue by mahmudur-adon** [f4him/plymouth-themes#1]
`sudo update-alternatives --install /lib/plymouth/themes/default.plymouth default.plymouth /lib/plymouth/themes/Hitman/hitman.plymouth 100`
this line is not working.

**Comment by f4him** [comment]
@mahmudur-adon fixed the paths, should be working now.

**Comment by f4him** [comment]
check https://github.com/f4him/plymouth-themes/commit/19ff70e5da5b654dd01a4a65b7aced67b8ab3c04
